name: main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.5"

      - name: Set up yabs
        run: go install github.com/jakegut/yabs/cmd/yabs@latest

      - name: Cache yabs
        uses: actions/cache@v3
        with:
          path: .yabs

      - name: lint
        run: yabs lint

      - name: test
        run: yabs test
